POST http://localhost:8080/api/member/review
Content-Type: application/json

{
  "image" : "test",
  "title" : "test",
  "author" : "test",
  "publisher" : "test",
  "review" : "testreview"
}

###
POST http://localhost:8080/api/issue/token
Content-Type: application/json
Refresh-Token :  eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZWppbjEyIiwiZXhwIjoxNjYyMzQwOTY1LCJpYXQiOjE2NjIzNDA5MzV9.vaYDsS-uoZ2BOtc7ta4sey3vwU5kC3cVG7goZl7W9No
{}

###
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "username" : "sejin12",
  "password" : "sejin12"
}

###
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "username" : "sejin12",
  "password" : "sejin12"
}

###
